# Generated by Django 5.0.6 on 2024-07-07 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_item_dscription_remove_item_name_item_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='blood_type',
        ),
        migrations.RemoveField(
            model_name='item',
            name='height',
        ),
        migrations.RemoveField(
            model_name='item',
            name='number_of_siblings',
        ),
        migrations.RemoveField(
            model_name='item',
            name='weight',
        ),
    ]
